var profile = {      
    basePath: "./scripts/", 
    releaseDir: "../release/scripts",
    layerOptimize: "shrinksafe.keepLines", 
    hasReport: true,
	localeList: "en,pt,pt-br", 
    action: "release",
    optimize: "closure",
    mini: true,
	cssOptimize: true,

    defaultConfig: {
        hasCache:{
           "dojo-built": 1,
           "dojo-loader": 1,
           "dom": 1,
           "host-browser": 1,
           "config-selectorEngine": "lite"
        }
	},

    packages:[ 
    {
        name: "manager",
        location: "manager"
    },
    {
        name: "dojo",
        location: "dojo"
    },
    {
        name: "dijit",
        location: "dijit"
    },
    {
        name: "dojox",
        location: "dojox"
    },
    {
        name: "dgrid",
        location: "dgrid"
    },
    {
        name: "xstyle",
        location: "xstyle"
    },
    {
        name: "put-selector",
        location: "put-selector"
    }
    ], 

	layers: {
        "manager/main": {
            include: [
			"dojo/cldr/nls/currency",
			"dojo/cldr/nls/number",
			"dojo/cldr/nls/gregorian",
			"dojo/fx/Toggler",
            "dijit/_base",
            "dijit/_Widget",
            "dijit/_Templated",
            "dijit/_WidgetBase",
            "dijit/_TemplatedMixin",
            "dijit/_CssStateMixin",
            "dijit/registry",
            "dijit/form/_FormMixin",
			"dijit/ColorPalette",
            "dijit/Dialog",
            "dijit/Editor",
            "dijit/Menu",
            "dijit/MenuBar",
            "dijit/MenuBarItem",
			"dijit/PopupMenuBarItem",
			"dijit/PopupMenuItem",
			"dijit/CheckedMenuItem",
            "dijit/Toolbar",
            "dijit/Tooltip",
            "dijit/Tree",
            "dijit/WidgetSet",
            "dijit/PopupMenuItem",
            "dijit/tree/ForestStoreModel",
            "dijit/tree/ObjectStoreModel",
            "dijit/TooltipDialog",
            "dijit/_editor/plugins/FontChoice",
            "dijit/_editor/plugins/TextColor",
			"dojox/editor/plugins/PasteFromWord",
            "dojox/editor/plugins/TablePlugins",
			"dojox/widget/Standby",
            "dijit/form/Button",
            "dijit/form/CheckBox",
            "dijit/form/ComboBox",
            "dijit/form/CurrencyTextBox",
            "dijit/form/DateTextBox",
            "dijit/form/FilteringSelect",
            "dijit/form/Form",
            "dijit/form/MultiSelect",
            "dijit/form/NumberSpinner",
            "dijit/form/NumberTextBox",
            "dijit/form/RadioButton",
            "dijit/form/Select",
            "dijit/form/SimpleTextarea",
            "dijit/form/TextBox",
            "dijit/form/TimeTextBox",
            "dijit/form/ValidationTextBox",
            "dijit/form/ComboButton",
			"dijit/form/nls/pt/validate",
            "dijit/layout/AccordionContainer",
            "dijit/layout/AccordionPane",
            "dijit/layout/ContentPane",
            "dijit/layout/StackContainer",
            "dijit/layout/TabContainer",
            "dijit/layout/TabContainer",
            "dijit/layout/BorderContainer",
            "dojox/layout/ContentPane",
            "dojox/form/Uploader",
            "dojox/form/uploader/FileList",
            "dojox/form/uploader/plugins/IFrame",
            "dojox/validate",
            "dojox/validate/br",
            "dojox/validate/web",
            "dojox/html/styles",
			"dojox/widget/Standby",
			"xstyle/css",
			"xstyle/load-css",
			"xstyle/has-class",
			"dgrid/List", 
			"dgrid/OnDemandGrid", 
			"dgrid/Selection",
            "dgrid/Keyboard", 
			"dgrid/util/misc",
			"dgrid/util/mouse",	
			"dgrid/util/touch",
            "manager/Utils",
            "manager/Hash",
            "manager/MD5",
            "manager/Core",
            "manager/Ajax",
            "manager/Page",
            "manager/UTF8",
            "manager/Base64",
            "manager/Patches",
            "manager/ElementPane",
            "manager/Form",
            "manager/ComboBox",
            "manager/Currency",
            "manager/BoxPane",
            "manager/DateTextBox",
            "manager/DGrid",
            "manager/Dialog",
            "manager/DialogSimple",
            "manager/DnD",
            "manager/EditMask",
            "manager/Grid",
            "manager/GridInput",
            "manager/DataGrid",
            "manager/GridPages",
            "manager/Lookup",
            "manager/FormPopup",
            "manager/MultiTextField",
            "manager/MultiTextField2",
            "manager/MultiSelection",
            "manager/TextTable",
            "manager/TransferBox",
            "manager/Validate",
            "manager/ValidationTextarea",
            "manager/Tree",
            "manager/Window"
            ],
			includeLocales: ["en", "pt", "pt-br"] 
		}
    }
};
